# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03576fd9a33af0cd6a3f8e702440f4256b3bb6f79299171e9eee88c973993fa4ed68fef448e8c0e321a63d53d4c9d063b1604ee8167746301854f9a2b9faf3e6

test:
  secret_key_base: ec69d907b345e1d7e425075fb3661e5632198c46dd2d3e99d69a3f8aa59519137a1ad712de643f7ad0bd7fb2c829b0a0a798c01447941380b1fb469f350341e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
